# Generated by Django 3.1.4 on 2020-12-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0002_auto_20201227_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
