# Generated by Django 3.1.4 on 2020-12-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0003_project_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tagline',
            new_name='short_description',
        ),
    ]
