# Generated by Django 3.1.4 on 2020-12-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0006_auto_20201228_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('EN DESARROLLO', 'EN DESARROLLO'), ('EN PRODUCCIÓN', 'EN PRODUCCIÓN'), ('INACTIVO', 'INACTIVO')], max_length=14),
        ),
    ]
