# Generated by Django 3.1.4 on 2021-01-01 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nexus', '0007_auto_20201228_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('BAJA', 'BAJA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA')], max_length=5)),
                ('status', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('ASIGNADO', 'ASIGNADO'), ('EN DESARROLLO', 'EN DESARROLLO'), ('CERRADO', 'CERRADO')], max_length=13)),
                ('type', models.CharField(choices=[('FEATURE', 'FEATURE'), ('BUG', 'BUG'), ('DISEÑO', 'DISEÑO')], max_length=7)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
