# Generated by Django 3.1.4 on 2021-01-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0010_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NUEVO', 'NUEVO'), ('ASIGNADO', 'ASIGNADO'), ('EN DESARROLLO', 'EN DESARROLLO'), ('CERRADO', 'CERRADO')], default='NUEVO', max_length=13),
        ),
    ]
