# Generated by Django 3.1.4 on 2021-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0011_auto_20210109_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
