# Generated by Django 3.1.4 on 2021-02-04 04:21

from django.db import migrations, models
import nexus.models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0017_auto_20210204_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=nexus.models.get_project_upload_path),
        ),
    ]
