# Generated by Django 3.1.4 on 2021-02-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0018_auto_20210204_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
    ]
