# Generated by Django 3.1.4 on 2021-02-20 05:53

from django.db import migrations, models
import nexus.models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0019_auto_20210218_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=nexus.models.get_user_image_upload_path),
        ),
    ]
