# Generated by Django 3.1.4 on 2021-04-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0021_project_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='team',
            new_name='team_members',
        ),
    ]
